export const INITIAL_LOAD_BOARDS = "INITIAL_LOAD_BOARDS";
export const INITIAL_LOAD_CARDS = "INITIAL_LOAD_CARDS";
export const INITIAL_LOAD_COMMENTS = "INITIAL_LOAD_COMMENTS";
export const INITIAL_USER = "INITIAL_USER";

export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const ENTER_TEXT = "ENTER_TEXT";

export const UPDATE_BOARD_NAME = "UPDATE_BOARD_NAME";

export const ADD_CARD = "ADD_CARD";
export const DELETE_CARD = "DELETE_CARD";
export const UPDATE_CARD_NAME = "UPDATE_CARD_NAME";

export const ADD_CARD_DESCRIPTION = "ADD_CARD_DESCRIPTION";

export const ADD_COMMENT_CARD = "ADD_COMMENT_CARD";
export const UPDATE_COMMENT_CARD = "UPDATE_COMMENT_CARD";
export const DELETE_COMMENT_CARD = "DELETE_COMMENT_CARD";
